# Amazon "All Beauty" Review Scraper BATCH 2 

This notebook targets NEW products not already present in the batch-1 dataset.
It writes to entirely separate output files and never reads or modifies the batch-1
CSV except to build an exclude-list of ASINs. 

Target: 6,000 reviews/year for 2024, 2025, 2026 (18,000 total), from products not
already scraped in batch 1.

## 1. Setup

Only needs to be run once on first execution.

In [ ]:
# Only needs to be run once on first execution
!pip install playwright pandas python-dateutil langdetect deep-translator tqdm -q
!playwright install chromium

## 2. Imports

In [5]:
import asyncio
import csv
import hashlib
import json
import os
import random
import re
import shutil
import sys
import threading
import time
import uuid
from datetime import datetime, timezone
from pathlib import Path

from dateutil import parser as dateparser
from playwright.async_api import async_playwright

## 3. Settings

You can change the yearly quotas here. An equal quota (3500/3500/3500) is the option
that makes the year-over-year comparison statistically cleanest if you prefer a
quota proportional to organic volume (e.g., less for 2026, since the year is not yet
over), change the `PER_YEAR_QUOTA` dictionary, but justify this choice in the thesis
methodology.

In [6]:
CATEGORY_SEARCH_URL = "https://www.amazon.de/s?i=beauty&s=review-rank"
MIN_DATE = datetime(2024, 1, 1)

PER_YEAR_QUOTA = {
    2024: 6000,
    2025: 6000,
    2026: 6000,
}
TARGET_YEARS = sorted(PER_YEAR_QUOTA.keys())
TARGET_REVIEW_COUNT = sum(PER_YEAR_QUOTA.values())

ASIN_TARGET_COUNT = 6000  # larger pool since the target is doubled

# --- NEW: separate output files, batch-1 data is never touched ---
OUTPUT_CSV = "all_beauty_reviews_2024_2026_batch2.csv"
CHECKPOINT_FILE = "checkpoint_batch2.json"

# --- NEW: exclude products already collected in batch 1 ---
EXISTING_DATASET_PATH = r"C:\Users\Admin\Desktop\Pythonprojects\all_beauty_reviews_2024_2026_with_en.csv"  # your original batch-1 file (8,500 products)
import pandas as pd
try:
    _existing_df = pd.read_csv(EXISTING_DATASET_PATH, encoding="utf-8-sig", usecols=["asin"])
    EXCLUDE_ASINS = set(_existing_df["asin"].unique())
    print(f"{len(EXCLUDE_ASINS)} products from batch 1 will be excluded from batch 2.")
except FileNotFoundError:
    EXCLUDE_ASINS = set()
    print("WARNING: batch-1 file not found at the path above — no products excluded. "
          "Check EXISTING_DATASET_PATH before running the real scrape.")

RANDOM_SEED = 43  # different seed from batch 1, extra safety against overlap

SCRAPE_SESSION_ID = f"{datetime.utcnow():%Y%m%dT%H%M%S}_{uuid.uuid4().hex[:6]}"

PROXY_LIST = [
    # "http://user:pass@proxy1.example.com:8000",
]

MIN_DELAY, MAX_DELAY = 4.0, 9.0
MAX_PAGES_PER_PRODUCT = 200
MAX_REVIEWS_PER_PRODUCT = 500
MAX_CONSECUTIVE_NO_PROGRESS_PAGES = 15
HEADLESS = False

USER_DATA_DIR = "amazon_browser_profile"  # same browser profile/login as batch 1

FIELDNAMES = [
    "asin", "rating", "title", "text", "images",
    "user_id", "user_id_missing_reason", "user_profile_href_raw",
    "review_id", "review_id_is_fallback",
    "unix_time", "date", "verified", "helpful",
    "page_number", "scrape_session_id", "scraped_at",
]

1507 products from batch 1 will be excluded from batch 2.

C:\Users\Admin\AppData\Local\Temp\ipykernel_19732\4144383341.py:32: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  SCRAPE_SESSION_ID = f"{datetime.utcnow():%Y%m%dT%H%M%S}_{uuid.uuid4().hex[:6]}"

## 4. Helper functions (checkpoint, proxy, delay, fallback id, quota check)

In [7]:
def load_checkpoint():
    if Path(CHECKPOINT_FILE).exists():
        state = json.loads(Path(CHECKPOINT_FILE).read_text())
        state.setdefault("year_counts", {})
        return state
    return {"scraped_asins": [], "total_reviews": 0, "year_counts": {}}


def save_checkpoint(state):
    Path(CHECKPOINT_FILE).write_text(json.dumps(state))


def get_proxy():
    return random.choice(PROXY_LIST) if PROXY_LIST else None


async def human_delay():
    await asyncio.sleep(random.uniform(MIN_DELAY, MAX_DELAY))


def make_fallback_review_id(asin, user_id, unix_time, text):
    raw = f"{asin}|{user_id}|{unix_time}|{(text or '')[:80]}"
    return "fallback_" + hashlib.sha1(raw.encode("utf-8")).hexdigest()[:16]


def year_count(state, year):
    return state["year_counts"].get(str(year), 0)


def year_quota_full(state, year):
    if year not in PER_YEAR_QUOTA:
        return True  # year outside the target range -> will not be written anyway
    return year_count(state, year) >= PER_YEAR_QUOTA[year]


def all_quotas_met(state):
    return all(year_quota_full(state, y) for y in TARGET_YEARS)

## 5. Collecting ASINs (+ shuffling)

In [8]:
async def collect_asins(page, target_count=500, exclude=None):
    exclude = exclude or set()
    asins = set()
    url = CATEGORY_SEARCH_URL
    page_num = 1
    empty_pages_in_a_row = 0

    while len(asins) < target_count and page_num <= 400:
        await page.goto(f"{url}&page={page_num}", timeout=60000)
        await human_delay()

        before_count = len(asins)
        links = await page.locator("a[href*='/dp/']").all()
        for link in links:
            href = await link.get_attribute("href")
            if href:
                m = re.search(r"/dp/([A-Z0-9]{10})", href)
                if m:
                    candidate = m.group(1)
                    if candidate not in exclude:
                        asins.add(candidate)

        new_this_page = len(asins) - before_count
        print(f"[ASIN collection] page {page_num} -> total {len(asins)} NEW products (+{new_this_page})")

        if new_this_page == 0:
            empty_pages_in_a_row += 1
            if empty_pages_in_a_row >= 3:
                print("No new products for 3 pages in a row, results exhausted, stopping.")
                break
        else:
            empty_pages_in_a_row = 0

        page_num += 1

    asin_list = list(asins)[:target_count]

    rng = random.Random(RANDOM_SEED)
    rng.shuffle(asin_list)

    return asin_list

## 6. Review scraping (with yearly quota)

Difference: once a year's quota is full, reviews for that year are not written,
but pagination continues in order to reach older years. If all yearly quotas are
full, both the product and the entire crawl are terminated early (to avoid
unnecessary requests).

In [ ]:
GERMAN_MONTHS = {
    "Januar": 1, "Februar": 2, "März": 3, "April": 4, "Mai": 5, "Juni": 6,
    "Juli": 7, "August": 8, "September": 9, "Oktober": 10,
    "November": 11, "Dezember": 12,
}

def parse_review_date(text):
    m = re.search(r"(\d{1,2})\.\s*(\w+)\s*(\d{4})", text)
    if m:
        day, month_name, year = m.groups()
        month = GERMAN_MONTHS.get(month_name)
        if month:
            return datetime(int(year), month, int(day))
    date_match = re.search(r"on (.+)$", text)
    if date_match:
        try:
            return dateparser.parse(date_match.group(1))
        except Exception:
            return None
    return None


async def scrape_reviews_for_asin(page, asin, writer, state):
    new_count = 0
    quota_skipped = 0
    stop = False
    seen_review_ids_this_product = set()
    consecutive_no_progress_pages = 0

    for page_num in range(1, MAX_PAGES_PER_PRODUCT + 1):
        if stop:
            break
        if new_count >= MAX_REVIEWS_PER_PRODUCT:
            print(f"  {asin}: per-product write limit reached ({MAX_REVIEWS_PER_PRODUCT})")
            break
        if all_quotas_met(state):
            print("  All yearly quotas are full, terminating this product and the crawl.")
            stop = True
            break
        if consecutive_no_progress_pages >= MAX_CONSECUTIVE_NO_PROGRESS_PAGES:
            print(f"  {asin}: no progress for {MAX_CONSECUTIVE_NO_PROGRESS_PAGES} pages "
                  f"(likely stuck on a quota-full year), abandoning product, moving to next.")
            break

        review_url = (
            f"https://www.amazon.de/product-reviews/{asin}"
            f"?sortBy=recent&pageNumber={page_num}"
        )
        try:
            await page.goto(review_url, timeout=60000)
        except Exception as e:
            print(f"  [error] {asin} page {page_num}: {e}")
            break

        await human_delay()

        review_blocks = await page.locator("[data-hook='review']").all()
        if not review_blocks:
            break

        repeats_this_page = 0
        new_count_before_this_page = new_count

        for block in review_blocks:
            try:
                date_el = block.locator("span[data-hook='review-date']")
                if await date_el.count() == 0:
                    continue
                date_raw = await date_el.first.inner_text()
                review_date = parse_review_date(date_raw)
                if review_date is None:
                    continue
                if review_date < MIN_DATE:
                    stop = True
                    break

                year = review_date.year

                rating = None
                rating_el = block.locator(
                    "i[data-hook='review-star-rating'] span, "
                    "i[data-hook='cmps-review-star-rating'] span"
                )
                if await rating_el.count() > 0:
                    rating_raw = await rating_el.first.inner_text()
                    rm = re.search(r"([\d.,]+)", rating_raw)
                    if rm:
                        rating = float(rm.group(1).replace(",", "."))

                title = ""
                title_el = block.locator("[data-hook='review-title']")
                if await title_el.count() > 0:
                    title = (await title_el.first.inner_text()).strip()

                body_el = block.locator("span[data-hook='review-body']")
                body = await body_el.first.inner_text() if await body_el.count() > 0 else ""
                body_clean = body.strip()

                verified = await block.locator("span[data-hook='avp-badge']").count() > 0

                helpful_el = block.locator("span[data-hook='helpful-vote-statement']")
                helpful_votes = 0
                if await helpful_el.count() > 0:
                    helpful_text = await helpful_el.first.inner_text()
                    hm = re.search(r"\d+", helpful_text)
                    if hm:
                        helpful_votes = int(hm.group())

                user_id = None
                user_id_missing_reason = None
                user_profile_href_raw = None
                profile_link = block.locator("a.a-profile")
                if await profile_link.count() > 0:
                    href = await profile_link.first.get_attribute("href")
                    if href:
                        user_profile_href_raw = href
                        m = re.search(r"account\.([A-Z0-9]+)", href)
                        if m:
                            user_id = m.group(1)
                        else:
                            user_id_missing_reason = "unparsed_href"
                    else:
                        user_id_missing_reason = "profile_link_no_href"
                else:
                    user_id_missing_reason = "no_profile_link"

                image_urls = []
                img_els = await block.locator(
                    "div[data-hook='review-image-tile-section'] img"
                ).all()
                for img in img_els:
                    src = await img.get_attribute("src")
                    if src:
                        image_urls.append(src)

                timestamp = int(review_date.replace(tzinfo=timezone.utc).timestamp())

                review_id = None
                review_id_is_fallback = False
                raw_id = await block.get_attribute("id")
                # Verified via live DOM inspection: the real review id is stored
                # directly as id="R3ALT25L04Y8PS", WITHOUT the "customer_review-"
                # prefix. That prefix is separately available in the
                # data-csa-c-slot-id attribute, which we use as a fallback source.
                if raw_id and re.match(r"^R[A-Z0-9]{8,}$", raw_id):
                    review_id = raw_id
                if not review_id:
                    slot_id = await block.get_attribute("data-csa-c-slot-id")
                    if slot_id and "customer_review-" in slot_id:
                        review_id = slot_id.split("customer_review-")[-1]
                if not review_id:
                    review_id = make_fallback_review_id(asin, user_id, timestamp, body_clean)
                    review_id_is_fallback = True

                # not only skip in-session for a REAL review_id 
                # Since the fallback id is content-based (hash), two different real
                # reviews (e.g., a bot genuinely posting the same text twice) could
                # collide on the same fallback hash. If we skipped in that case, we
                # would lose exactly the signal we are trying to capture. Therefore
                # rows with a fallback id are NEVER skipped in-session; all of them
                # are written, and the distinction is left to the post-hoc
                # is_content_duplicate flag (which also does not delete, only flags).
                if (not review_id_is_fallback) and (review_id in seen_review_ids_this_product):
                    repeats_this_page += 1
                    continue
                seen_review_ids_this_product.add(review_id)

                # --- NEW: yearly quota check ---
                # If the quota is full, we do NOT write this row, but we keep
                # paginating (to reach older years) -> no information loss, we
                # only prevent unbalanced accumulation.
                if year_quota_full(state, year):
                    quota_skipped += 1
                    continue

                writer.writerow({
                    "asin": asin,
                    "rating": rating,
                    "title": title,
                    "text": body_clean,
                    "images": "|".join(image_urls),
                    "user_id": user_id,
                    "user_id_missing_reason": user_id_missing_reason,
                    "user_profile_href_raw": user_profile_href_raw,
                    "review_id": review_id,
                    "review_id_is_fallback": review_id_is_fallback,
                    "unix_time": timestamp,
                    "date": review_date.strftime("%Y-%m-%d"),
                    "verified": verified,
                    "helpful": helpful_votes,
                    "page_number": page_num,
                    "scrape_session_id": SCRAPE_SESSION_ID,
                    "scraped_at": datetime.utcnow().isoformat(),
                })
                new_count += 1
                state["total_reviews"] += 1
                state["year_counts"][str(year)] = year_count(state, year) + 1

            except Exception as ex:
                print(f"    [row skipped] {ex}")
                continue

        if new_count == new_count_before_this_page:
            consecutive_no_progress_pages += 1
        else:
            consecutive_no_progress_pages = 0

        print(f"  {asin} page {page_num}: +{new_count} written, {quota_skipped} skipped-quota-full, "
              f"{repeats_this_page}/{len(review_blocks)} already seen, "
              f"no-progress pages: {consecutive_no_progress_pages}/{MAX_CONSECUTIVE_NO_PROGRESS_PAGES} "
              f"| year status: {dict(state['year_counts'])}")

        if review_blocks and repeats_this_page == len(review_blocks):
            print(f"  {asin}: this page is entirely a repeat (drift/loop), product finished.")
            break

    return new_count

## 7. Main function

In [10]:
async def main():
    state = load_checkpoint()
    already_done = set(state["scraped_asins"])

    file_exists = Path(OUTPUT_CSV).exists()
    csv_file = open(OUTPUT_CSV, "a", newline="", encoding="utf-8-sig")
    writer = csv.DictWriter(csv_file, fieldnames=FIELDNAMES)
    if not file_exists:
        writer.writeheader()

    async with async_playwright() as p:
        proxy = get_proxy()
        launch_kwargs = {
            "user_data_dir": USER_DATA_DIR,
            "headless": HEADLESS,
            "locale": "en-GB",
            "user_agent": (
                "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
                "AppleWebKit/537.36 (KHTML, like Gecko) "
                "Chrome/125.0.0.0 Safari/537.36"
            ),
        }
        if proxy:
            launch_kwargs["proxy"] = {"server": proxy}

        context = await p.chromium.launch_persistent_context(**launch_kwargs)
        page = context.pages[0] if context.pages else await context.new_page()

        print("Collecting ASIN list (excluding batch-1 products)...")
        asins = await collect_asins(page, target_count=ASIN_TARGET_COUNT, exclude=EXCLUDE_ASINS)
        print(f"{len(asins)} new products found (shuffled order). Starting review scan.\n")
        print(f"Target: {dict(PER_YEAR_QUOTA)} (total {TARGET_REVIEW_COUNT})\n")

        for asin in asins:
            if all_quotas_met(state):
                print("All yearly quotas are full, stopping the crawl.")
                break
            if asin in already_done:
                continue

            await scrape_reviews_for_asin(page, asin, writer, state)
            state["scraped_asins"].append(asin)
            save_checkpoint(state)
            csv_file.flush()

        await context.close()

    csv_file.close()
    print(f"\nDone. Total {state['total_reviews']} reviews -> {OUTPUT_CSV}")
    print(f"Year distribution: {dict(state['year_counts'])}")

## 7b. Initial setup: manual login (ONE TIME ONLY)

In [11]:
async def _manual_login():
    async with async_playwright() as p:
        context = await p.chromium.launch_persistent_context(
            USER_DATA_DIR,
            headless=False,
            locale="en-GB",
            user_agent=(
                "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
                "AppleWebKit/537.36 (KHTML, like Gecko) "
                "Chrome/125.0.0.0 Safari/537.36"
            ),
        )
        page = context.pages[0] if context.pages else await context.new_page()
        await page.goto("https://www.amazon.de", timeout=60000)
        await page.wait_for_timeout(1500)
        try:
            await page.click("#nav-link-accountList", timeout=10000)
        except Exception:
            print("Login link not found automatically, click the 'Sign in' link manually in the browser.")
        print("Log in manually in the browser (using a separate/disposable account).")
        print("After logging in, come back here and press Enter...")
        input()
        await context.close()
        print("Session saved:", USER_DATA_DIR)

def _run_login():
    if sys.platform == "win32":
        asyncio.set_event_loop_policy(asyncio.WindowsProactorEventLoopPolicy())
    asyncio.run(_manual_login())

# _run_login()  # uncomment and run during initial setup

## 7c. BACK UP old test data (do not delete!) (ONLY ONCE, before the real run)

In [ ]:
_ts = datetime.utcnow().strftime("%Y%m%dT%H%M%S")

if os.path.exists(CHECKPOINT_FILE):
    shutil.move(CHECKPOINT_FILE, f"{CHECKPOINT_FILE}.bak_{_ts}")
    print(f"checkpoint backed up -> {CHECKPOINT_FILE}.bak_{_ts}")

if os.path.exists(OUTPUT_CSV):
    shutil.move(OUTPUT_CSV, f"{OUTPUT_CSV}.bak_{_ts}")
    print(f"old CSV backed up -> {OUTPUT_CSV}.bak_{_ts}")

print("Clean, ready for the real run. (Old files were NOT deleted, they remain as .bak_*.)")

### 7d. Early quality check (run in a SEPARATE cell ~10-15 min after scraping starts)

In [ ]:
import pandas as pd
_df_peek = pd.read_csv(OUTPUT_CSV, encoding="utf-8-sig")
_before = len(_df_peek)
_unique_review_ids = _df_peek["review_id"].nunique()
print(f"So far: {_before} rows, unique review_id: {_unique_review_ids}")
if _before:
    print(f"review_id repeat rate: %{100*(1 - _unique_review_ids/_before):.2f}")
    print(f"fallback review_id rate: %{100*_df_peek['review_id_is_fallback'].mean():.2f}")
    print(f"missing user_id rate: %{100*_df_peek['user_id'].isna().mean():.2f}")
    _df_peek["year"] = pd.to_datetime(_df_peek["date"]).dt.year
    print("Year distribution (written so far):")
    print(_df_peek["year"].value_counts().sort_index())
    print("Target quota:", PER_YEAR_QUOTA)

## 8. Run

In [ ]:
def _run_scraper():
    if sys.platform == "win32":
        asyncio.set_event_loop_policy(asyncio.WindowsProactorEventLoopPolicy())
    asyncio.run(main())

scraper_thread = threading.Thread(target=_run_scraper)
scraper_thread.start()
scraper_thread.join()

C:\Users\Admin\AppData\Local\Temp\ipykernel_19732\70850797.py:3: DeprecationWarning: 'asyncio.WindowsProactorEventLoopPolicy' is deprecated and slated for removal in Python 3.16
  asyncio.set_event_loop_policy(asyncio.WindowsProactorEventLoopPolicy())
C:\Users\Admin\AppData\Local\Temp\ipykernel_19732\70850797.py:3: DeprecationWarning: 'asyncio.set_event_loop_policy' is deprecated and slated for removal in Python 3.16
  asyncio.set_event_loop_policy(asyncio.WindowsProactorEventLoopPolicy())

Collecting ASIN list (excluding batch-1 products)...

## 9. Check the result

In [8]:
import pandas as pd
df = pd.read_csv(OUTPUT_CSV, encoding="utf-8-sig")
df["year"] = pd.to_datetime(df["date"]).dt.year
print(df.shape)
print("Number of unique products:", df["asin"].nunique())
print("Average per product:", len(df) / df["asin"].nunique())
print("Number of empty/NaN text values:", df["text"].isna().sum())
print()
print("Year distribution (compare with target):")
print(df["year"].value_counts().sort_index())
print("Target quota:", PER_YEAR_QUOTA)
print()
print("Reasons for missing user_id:")
print(df["user_id_missing_reason"].value_counts(dropna=True))
print("Fallback review_id rate: %{:.2f}".format(100 * df["review_id_is_fallback"].mean()))
df.head()

(13872, 18)
Number of unique products: 2348
Average per product: 5.908006814310051
Number of empty/NaN text values: 8

Year distribution (compare with target):
year
2024    1872
2025    6000
2026    6000
Name: count, dtype: int64
Target quota: {2024: 6000, 2025: 6000, 2026: 6000}

Reasons for missing user_id:
user_id_missing_reason
no_profile_link    535
Name: count, dtype: int64
Fallback review_id rate: %0.00

,asin,rating,title,text,images,user_id,user_id_missing_reason,user_profile_href_raw,review_id,review_id_is_fallback,unix_time,date,verified,helpful,page_number,scrape_session_id,scraped_at,year
0,B083TXY188,5.0,"5,0 von 5 Sternen\n Guter Preis",Für mich toller Geruch\nSehr schnelle Lieferung,NaN,[REDACTED],NaN,/gp/profile/amzn1.account.[REDACTED],R2LHUH3L5EDF8N,False,1786320000,2026-08-10,True,0,1,20260905T100723_da62e9,2026-09-05T10:52:22.515199,2026
1,B083TXY188,5.0,"5,0 von 5 Sternen\n Super",Super,NaN,[REDACTED],NaN,/gp/profile/amzn1.account.[REDACTED],R15ALY5O6AZQ6N,False,1783814400,2026-07-12,True,0,1,20260905T100723_da62e9,2026-09-05T10:52:22.616720,2026
2,B083TXY188,4.0,"4,0 von 5 Sternen\n Escada",Sam zapach jest cudowny.U mnie ten zapach nie ...,NaN,[REDACTED],NaN,/gp/profile/amzn1.account.[REDACTED],RR1WUEHWCNWZM,False,1780531200,2026-06-04,True,0,1,20260905T100723_da62e9,2026-09-05T10:52:22.734487,2026
3,B083TXY188,5.0,"5,0 von 5 Sternen\n wunderschöne Geruch",Sehr gute Qualität. Spezielle Aroma. Ich würde...,NaN,[REDACTED],NaN,/gp/profile/amzn1.account.[REDACTED],R11DYW5Z37E1FG,False,1780185600,2026-05-31,True,0,1,20260905T100723_da62e9,2026-09-05T10:52:22.853235,2026
4,B083TXY188,5.0,"5,0 von 5 Sternen\n Lieblingsduft",mein Lieblingsduft schon seit vielen Jahren ab...,NaN,[REDACTED],NaN,/gp/profile/amzn1.account.[REDACTED],R2OQGGA32HQLBM,False,1777680000,2026-05-02,True,0,1,20260905T100723_da62e9,2026-09-05T10:52:22.963177,2026

### 9a. Duplicate analysis — NO DELETION, FLAGS ONLY

In [9]:
import numpy as np

df = pd.read_csv(OUTPUT_CSV, encoding="utf-8-sig")

df["is_review_id_duplicate"] = df.duplicated(subset=["review_id"], keep=False) & (~df["review_id_is_fallback"])

key_cols = ["asin", "rating", "title", "text", "user_id", "unix_time"]
df_key = df[key_cols].astype(str)
df["is_content_duplicate"] = df_key.duplicated(keep=False)

df_valid_uid = df[df["user_id"].notna()].copy()
df_sorted = df_valid_uid.sort_values(["user_id", "unix_time"])
df_sorted["prev_asin"] = df_sorted.groupby("user_id")["asin"].shift(1)
df_sorted["prev_time"] = df_sorted.groupby("user_id")["unix_time"].shift(1)
df_sorted["time_diff"] = df_sorted["unix_time"] - df_sorted["prev_time"]
burst_mask = (
    df_sorted["prev_asin"].notna() &
    (df_sorted["prev_asin"] != df_sorted["asin"]) &
    (df_sorted["time_diff"].abs() <= 3600)
)
burst_user_ids = set(df_sorted.loc[burst_mask, "user_id"].unique())
df["is_cross_asin_burst"] = df["user_id"].isin(burst_user_ids)

print("review_id duplicate:", df["is_review_id_duplicate"].sum())
print("content-key duplicate:", df["is_content_duplicate"].sum())
print("cross-ASIN burst:", df["is_cross_asin_burst"].sum())

FLAGGED_CSV = "all_beauty_reviews_2024_2026_flagged.csv"
df.to_csv(FLAGGED_CSV, index=False, encoding="utf-8-sig")
print("Saved (raw file UNCHANGED):", FLAGGED_CSV)

review_id duplicate: 1045
content-key duplicate: 0
cross-ASIN burst: 1223
Saved (raw file UNCHANGED): all_beauty_reviews_2024_2026_flagged.csv

### 9b. Check the year distribution

In [10]:
df_check = pd.read_csv(OUTPUT_CSV, encoding="utf-8-sig")
df_check["year"] = pd.to_datetime(df_check["date"]).dt.year
print(df_check["year"].value_counts().sort_index())
print()
print("Percentage distribution:")
print((df_check["year"].value_counts(normalize=True).sort_index() * 100).round(1))
print()
print("Comparison against target quota:")
for y in TARGET_YEARS:
    actual = (df_check["year"] == y).sum()
    target = PER_YEAR_QUOTA[y]
    print(f"  {y}: {actual}/{target} (%{100*actual/target:.1f})")

year
2024    1872
2025    6000
2026    6000
Name: count, dtype: int64

Percentage distribution:
year
2024    13.5
2025    43.3
2026    43.3
Name: proportion, dtype: float64

Comparison against target quota:
  2024: 1872/6000 (%31.2)
  2025: 6000/6000 (%100.0)
  2026: 6000/6000 (%100.0)

## 10. Add multilingual, deterministic translation

In [11]:
import langdetect
from deep_translator import GoogleTranslator
from tqdm import tqdm
import time
import pandas as pd

langdetect.DetectorFactory.seed = 0  # deterministic language detection

df = pd.read_csv(FLAGGED_CSV, encoding="utf-8-sig")
print("Total Rows:", len(df))

def detect_lang(text):
    if not isinstance(text, str) or len(text.strip()) < 3:
        return None
    try:
        return langdetect.detect(text)
    except Exception:
        return None

tqdm.pandas(desc="Language detection")
df["detected_lang"] = df["text"].progress_apply(detect_lang)
print(df["detected_lang"].value_counts())

_translation_cache = {}

def translate_text(text, lang, max_retries=3):
    if not isinstance(text, str) or not text.strip():
        return pd.NA, "empty"
    if lang == "en":
        return text, "passthrough"

    cache_key = (lang, text)
    if cache_key in _translation_cache:
        return _translation_cache[cache_key], "translated_cached"

    src = lang if lang else "auto"
    for attempt in range(max_retries):
        try:
            result = GoogleTranslator(source=src, target="en").translate(text)
            if result:
                _translation_cache[cache_key] = result
                return result, "translated"
            return pd.NA, "empty_result"
        except Exception:
            if attempt == max_retries - 1:
                return pd.NA, "failed"
            time.sleep(1.5 * (attempt + 1))  # gradual backoff, against rate limits

text_results, text_status = [], []
for _, row in tqdm(df.iterrows(), total=len(df), desc="Translating text"):
    r, s = translate_text(row["text"], row["detected_lang"])
    text_results.append(r); text_status.append(s)
df["text_en"] = text_results
df["translation_status"] = text_status

title_results = []
for _, row in tqdm(df.iterrows(), total=len(df), desc="Translating title"):
    r, _s = translate_text(row["title"], row["detected_lang"])
    title_results.append(r)
df["title_en"] = title_results

print(df["translation_status"].value_counts())

TRANSLATED_CSV = "all_beauty_reviews_2024_2026_with_en.csv"
df.to_csv(TRANSLATED_CSV, index=False, encoding="utf-8-sig")
print(f"Done. Saved: {TRANSLATED_CSV}")
df[["text", "detected_lang", "text_en", "translation_status"]].sample(min(10, len(df)))

Total Rows: 13872

Language detection: 100%|██████████| 13872/13872 [02:27<00:00, 94.20it/s]

detected_lang
de    10795
en     1314
fr      254
id      225
no      124
af       90
it       88
es       71
ca       70
et       64
da       63
pl       62
ro       61
nl       58
sv       47
fi       44
tr       44
so       36
pt       25
tl       22
hr       19
sk       18
cs       15
hu       11
sl        9
lt        9
ru        7
vi        7
ar        6
cy        6
lv        5
sq        5
sw        5
ja        3
fa        1
Name: count, dtype: int64

Translating text: 100%|██████████| 13872/13872 [4:14:51<00:00,  1.10s/it]
Translating title: 100%|██████████| 13872/13872 [2:47:32<00:00,  1.38it/s]

translation_status
translated           9313
translated_cached    1761
failed               1476
passthrough          1314
empty                   8
Name: count, dtype: int64
Done. Saved: all_beauty_reviews_2024_2026_with_en.csv

,text,detected_lang,text_en,translation_status
4615,Gutes Duftverhalten 👍\nQualität passt,de,Good scent behavior 👍\nQuality fits,translated
7079,Reinigt sehr mild und gründlich,de,Cleans very mildly and thoroughly,translated
10309,Super Produkt,id,Super Product,translated_cached
10811,"Sehr gute Handcreme, besser, als alle Cremes, ...",de,"Very good hand cream, better than any cream I'...",translated
8980,GUT FÜR TROCKENE HAARE,en,GUT FÜR TROCKENE HAARE,passthrough
1850,Alles gut .\nGibt aber bessere,de,It's all ok .\nBut there are better ones,translated
12441,Schöne kuschelige Waschlappen,de,Lovely cozy washcloths,translated_cached
5786,Zur Pflege von meinen Haaren - Naturlocken - g...,de,NaN,failed
3536,"Super Produkt,hält was es verspricht",de,"Great product, does what it promises",translated
4150,Liegt sehr gut in der Hand. Sehr gut!!!,de,NaN,failed

## 11. Final quality report

In [2]:
import pandas as pd

TRANSLATED_CSV = r"C:\Users\Admin\Downloads\all_beauty_reviews_2024_2026_with_en.csv"
df = pd.read_csv(TRANSLATED_CSV, encoding="utf-8-sig")

PER_YEAR_QUOTA = {
    2024: 6000,
    2025: 6000,
    2026: 6000,
}
TARGET_YEARS = sorted(PER_YEAR_QUOTA.keys())

print("=== SCRAPE QUALITY REPORT ===")
print(f"Total rows: {len(df)}")
print(f"Unique products: {df['asin'].nunique()}")
print(f"Unique users: {df['user_id'].nunique(dropna=True)}")
print()
df["year"] = pd.to_datetime(df["date"]).dt.year
print("Year distribution vs. target quota:")
for y in TARGET_YEARS:
    actual = (df["year"] == y).sum()
    target = PER_YEAR_QUOTA[y]
    print(f"  {y}: {actual}/{target} (%{100*actual/target:.1f})")
print()
print(f"review_id duplicate: {df['is_review_id_duplicate'].sum()} (%{100*df['is_review_id_duplicate'].mean():.2f})")
print(f"content-key duplicate: {df['is_content_duplicate'].sum()} (%{100*df['is_content_duplicate'].mean():.2f})")
print(f"cross-ASIN burst: {df['is_cross_asin_burst'].sum()} (%{100*df['is_cross_asin_burst'].mean():.2f})")
print(f"fallback review_id: {df['review_id_is_fallback'].sum()} (%{100*df['review_id_is_fallback'].mean():.2f})")
print(f"missing user_id: {df['user_id'].isna().sum()} (%{100*df['user_id'].isna().mean():.2f})")
print()
print("Language distribution:")
print(df["detected_lang"].value_counts())
print()
print("Translation status:")
print(df["translation_status"].value_counts())

=== SCRAPE QUALITY REPORT ===
Total rows: 13872
Unique products: 2348
Unique users: 12393

Year distribution vs. target quota:
  2024: 1872/6000 (%31.2)
  2025: 6000/6000 (%100.0)
  2026: 6000/6000 (%100.0)

review_id duplicate: 1045 (%7.53)
content-key duplicate: 0 (%0.00)
cross-ASIN burst: 1223 (%8.82)
fallback review_id: 0 (%0.00)
missing user_id: 535 (%3.86)

Language distribution:
detected_lang
de    10795
en     1314
fr      254
id      225
no      124
af       90
it       88
es       71
ca       70
et       64
da       63
pl       62
ro       61
nl       58
sv       47
fi       44
tr       44
so       36
pt       25
tl       22
hr       19
sk       18
cs       15
hu       11
sl        9
lt        9
ru        7
vi        7
ar        6
cy        6
lv        5
sq        5
sw        5
ja        3
fa        1
Name: count, dtype: int64

Translation status:
translation_status
translated           9313
translated_cached    1761
failed               1476
passthrough          1314
empty                   8
Name: count, dtype: int64